name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
        continue-on-error: true

      - name: Build project
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start mock LLM server
        run: |
          node scripts/mock-llm-server.js &
          echo $! > mock-server.pid
          sleep 5
          # Verify server is running
          curl -f http://localhost:1234/health || exit 1
          echo "Mock server is running on port 1234"

      - name: Test mock server
        run: |
          curl -X POST http://localhost:1234/v1/chat/completions \
            -H "Content-Type: application/json" \
            -d '{"messages":[{"role":"user","content":"Hello"}],"stream":false}' \
            --max-time 10 || echo "Mock server test failed"

      - name: Run Playwright tests
        run: npx playwright test --reporter=line
        env:
          CI: true
        timeout-minutes: 10

      - name: Stop mock LLM server
        if: always()
        run: |
          if [ -f mock-server.pid ]; then
            kill $(cat mock-server.pid) || true
            sleep 2
          fi

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30

